### ISSUE TITLE
Master is broken 07/06/2016 - when expiry was merged ...

### ISSUE THREAD

**Issue by gsrai** [gsrai/Pool-Request#14]
loser is a winner for some reason, see prod at the url: https://popping-heat-7651.firebaseapp.com/ladder
user sorin lost the game but is classed as a winner, perhaps i am being stupid and have read it wrong. please can i get a second pair of eyes. if this is a bug, then it was introduced when the branch expiry was merged. perhaps some logic was changed, should have qaed mored and written tests. we live and learn eh?

**Comment by lukehowkins** [comment]
I have fixed this, and the other. Have checked and looks fine 'in prod'
Feel free to check yourself. I will close this and the other if you are happy
